name: Act on artifact registrations and promotions
on:
  push:
    tags:
      - "**@v[0-9]+.[0-9]+**"

jobs:
  act:
    name: "Version registration: ${GITHUB_REF#refs/tags/}"
    runs-on: ubuntu-latest
    steps:
    - name: Print the tag
      run: |
        echo "yay ${GITHUB_REF#refs/tags/}"
